services:
  postgres:
    image: 'postgres:18'
    labels:
      - 'org.springframework.boot.ignore=true'
    environment:
      - 'POSTGRES_DB=apteczka'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=apteczka_admin'
    ports:
      - '5433:5432'
    volumes:
      - './db/init:/docker-entrypoint-initdb.d:ro'
